### ISSUE TITLE
Discord.js embed is not compatible with slash-create embed

### ISSUE THREAD

**Issue by Ionaru** [Snazzah/slash-create#275]
**Description**
It seems that the Discord.js `MessageEmbed` class is not compatible with the Slash-create `MessageEmbedOptions` interface, even though the `MessageEmbed` class is valid input in `context.send`.

**To Reproduce**
```ts
import { MessageEmbed } from 'discord.js';
import { CommandContext, SlashCommand, SlashCreator } from 'slash-create';

export class TestCommand extends SlashCommand {
    public constructor(creator: SlashCreator) {
        super(creator, {
            description: 'Test to show that embed type is incompatible.',
            name: 'test',
        });
    }

    public async run(context: CommandContext): Promise<void> {
        await context.defer(false);
        const embed = new MessageEmbed();
        embed.setTitle('Test');
        embed.setDescription('This is a test');
        await context.send({embeds: [embed]}); // error TS2322
    }
}
```

**Expected result**
No error about an incompatible type and the input should work.

**Actual result**
This error pops up during build:
```
error TS2322: Type 'MessageEmbed' is not assignable to type 'MessageEmbedOptions'.
  Types of property 'author' are incompatible.
    Type 'MessageEmbedAuthor | null' is not assignable to type 'EmbedAuthorOptions | undefined'.
      Type 'null' is not assignable to type 'EmbedAuthorOptions | undefined'.
```

**Other solutions**
Adding `@ts-ignore` above the line mutes the error and the command works, but this is bad practise.
![image](https://user-images.githubusercontent.com/3472373/161357383-34738dc8-a36a-49b1-b53e-7b39de0b3d57.png)

**Versions**
Discord.js: 13.6.0
Slash-create: 5.4.1

**Comment by Snazzah** [comment]
Per the [FAQ](https://slash-create.js.org/#/docs/main/latest/general/faq):
> slash-create doesn't support `discord.js`'s MessageEmbed out of the box.

**Comment by Ionaru** [comment]
Oh, my bad. Sorry!
